name: IdealSpawnPoint
version: 1.0.2
main: cn.kafei.isp.ideal_spawn_point.Ideal_spawn_point
api-version: 1.20
authors: [mckafei_CN | 1780412693]
softdepend: [Multiworld, SomeOtherWorldPlugin]

commands:
  isp:
    description: IdealSpawnPoint主命令
    usage: /isp <子命令>
    permission: idealspawn.use

permissions:
  idealspawn.add:
    description: 允许添加复活点
    default: op
  idealspawn.remove:
    description: 允许移除复活点
    default: op
  idealspawn.list:
    description: 允许列出复活点
    default: true
  idealspawn.list.all:
    description: 允许列出所有世界的复活点
    default: op
  idealspawn.removeall:
    description: 允许移除所有复活点
    default: op
  idealspawn.reload:
    description: 允许重载配置文件
    default: op

